### PR TITLE
Fix for `window is not defined at object`

### PR DESCRIPTION
**Pull request by debasisdev**
- `globalObject: 'this'` added to Webpack Config
- `npm audit fix` also applied to fix vulnerabilities

### CODE REVIEW

**Comment by delete** [comment]
Thanks @debasisdev !

**Comment by delete** [comment]
Fix #21

**Comment by delete** [comment]
Please @dpopescu, can you publish this new version? Thanks.

**Comment by dpopescu** [comment]
@delete done. It's up.
@debasisdev thanks for the fix.

**Pull request merged**
